[preface]
= Introduction to openPEPPOL and BIS


This {peppol} BIS provides a set of specifications for implementing a {peppol} business process.

This specification, is a Country Specification of the Peppol International model ({pint}). Any instance documents compliant to this specification will be compliant with the PINT.

The purpose of this document is to facilitate an efficient implementation and increased use of electronic collaboration regarding the billing process.


.Statement of copyright
****
This Peppol Business Interoperability Specification (Peppol BIS) document is a Country Specification based on the PINT. The restrictions on PINT implemented in this Peppol BIS are identified in the conformance statement provided in appendix A.

The copyright of PINT is owned by OpenPEPPOL and its members.cOpenPEPPOL AISBL holds the copyright of this Peppol BIS. 

This PEPPOL BIS document may not be modified, re-distribute, sold or repackaged in any other way without the prior consent of OpenPEPPOL AISBL.
****


== Document Structure

This document is structured as follows:

*	*Chapters 1 - 4* gives general information on the business processes, requirements and functionalities
*	*Chapter 5* describes the semantical data types
*	*Chapters 6 - 8* describes tax, calculations and rounding.
*	*Chapter 9* provides examples of selected parts of the invoice
*	*Chapter 10* gives details and links to all code lists used
*   *Chapter 11* gives information on PEPPOL identifiers
*	*Chapter 12* describes in detail central information elements.
*	*Chapters 13 and 14* provides information on validation and validation rules
*	*Annexes* give information on restrictions on top of the {PINT}.

== Scope

This document is concerned with clarifying requirements for ensuring interoperability  and provides guidelines for the support and implementation of these requirements. This document will also provide a detailed implementation guideline for the invoice and credit note transactions.

== Audience

The audience for this document is organisations wishing to be Peppol enabled for exchanging electronic invoices, and/or their ICT-suppliers. These organisations may be:

     * Service providers
     * Contracting Authorities (CA)
     * Economic Operators (EO)
     * Software Developers

More specifically, roles addressed are the following:

    * ICT Architects
    * ICT Developers
    * Business Experts

For further information on Peppol/OpenPEPPOL, please see {common}
