
= Calculation on line level

[[price-calc]]
== Item net price (IBT-146)

If gross price and discount exist, the Item net price has to equal with the item gross price less the item price discount.

Calculation formula:
====
stem:["Item net price" = "Item gross price (IBT-148)" - "Item price discount (IBT-147)"]
====

include::../../syntax/priceamount.adoc[]



[[lineamount-calc]]
== Invoice line net amount (IBT-131)

The invoice line net amount (IBT-131) is as the name implies the *net* amount without CT, and inclusive of line level allowance and charges.

The formula for calculating the invoice line net amount is:

====
stem:["Item line net amount" = (("Item net price (IBT-146)" div "Item price base quantity (IBT-149)")] +
stem:[times ("Invoiced Quantity (IBT-129)")] +
stem:[+ "Invoice line charge amount (IBT-141)" - "Invoice line allowance amount (IBT-136)"]
====

IMPORTANT: As the line net amount must be rounded to no decimals, please note that the different parts of the calculation must be rounded separately. +
I.e the result of
stem:["Item line net amount" = (("Item net price (IBT-146)" div "Item price base quantity (IBT-149)") times ("Invoiced Quantity (IBT-129)")]
must be rounded to no decimals, and the allowance/charge amounts are also rounded separately.

include::../../syntax/lineamount.adoc[]
